"""
Shared text preprocessing for text-based biomarkers.
--------------------------------------------------------------------------------
`src.utils.load_data.data_prep.text_preprocessing`

Shared preprocessing for both offline and online feature extraction.

"""
import re, nltk, unicodedata
from typing import Iterable, List

# Keep only characters we expect NLTK + our grammar features to handle
_ALLOWED_TEXT_CHARS_RE = re.compile(r"[^a-z0-9\s\.\?\!,;:'\"-]")

# Sentence-ending punctuation
_EOS_CHARACTERS: set = {".", "!", "?"}

# Perplexity minimum
MIN_UTT_WORDS_DEFAULT = 3


# --------------------------------------------------------------------------------
# Remove IPA / phonetic symbols
# --------------------------------------------------------------------------------
def strip_unsupported_text_chars(text: str) -> str:
    """
    Remove characters outside the supported English-text preprocessing set.

    It also avoids NLTK syllable-tokenizer warnings from symbols outside
    its sonority hierarchy.
    """
    # Normalize common unicode punctuation first.
    text = text.translate(str.maketrans({
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
        "\u00a0": " ",
    }))

    # Decompose accents when possible.
    # Example: café -> cafe
    text = unicodedata.normalize("NFKD", text)

    # Drop remaining non-ASCII characters (removes IPA symbols like ɝ and ɪ)
    text = text.encode("ascii", "ignore").decode("ascii")

    # Remove any remaining unsupported ASCII symbols.
    text = _ALLOWED_TEXT_CHARS_RE.sub(" ", text)

    # Clean spacing again after removals.
    return re.sub(r"\s+", " ", text).strip()

# --------------------------------------------------------------------------------
# Text Normalization
# --------------------------------------------------------------------------------
def normalize_text(text: str) -> str:
    """
    Standardize the raw utterance text for biomarker calculations.
    Steps:
      1. Lowercase
      2. Strip unsupported unicode / IPA characters
      3. Collapse repeated whitespace
      4. Strip leading/trailing whitespace
    """
    text = text.lower()
    text = strip_unsupported_text_chars(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# --------------------------------------------------------------------------------
# Convert NLTK contraction tokens to full words
# --------------------------------------------------------------------------------
def replace_contraction_tokens(tokens: Iterable[str]) -> List[str]:
    """
    NLTK tunrs contractions into these kinds of tokens with apostraphes included,
    we change some of the known ones to full words.
    """
    # Mapping for tokens specifically generated by NLTK word_tokenize
    CONTRACTION_MAP = {
        "n't" : "not",
        "'re" : "are",
        "'ve" : "have",
        "'s"  : "is",
        "'ll" : "will",
        "'d"  : "would",
        "'m"  : "am",
        "wo"  : "will",  # NLTK splits  won't -> [wo,  n't]
        "ca"  : "can",   # NLTK splits  can't -> [ca,  n't]
        "sha" : "shall"  # NLTK splits shan't -> [sha, n't]
    }
    return [CONTRACTION_MAP.get(token, token) for token in tokens]

# ================================================================================
# NLTK Preprocessing
# ================================================================================
def preprocess(text: str):
    """
    Returns:
        cleaned  => normalized text
        tokens   => NLTK word_tokenize output
        pos_tags => NLTK pos_tag output
    """
    # 1. Lowercase + clean whitespace
    cleaned = normalize_text(text)
    if not cleaned: return "", [], []

    # 2. NLTK word_tokenize
    tokens = nltk.word_tokenize(cleaned)
    if not tokens: return cleaned, [], []

    # 3. NLTK pos_tag (returns list of (token, tag) tuples)
    tokens = replace_contraction_tokens(tokens)
    pos_tags = nltk.pos_tag(tokens)

    return cleaned, tokens, pos_tags


# ================================================================================
# Transcript Artifact Cleanup (ADReSS-M / IU dataset-specific)
# ================================================================================
def replace_helper(sentence: str) -> str:
    """Fix known informal spellings found in manual ADReSS-M transcripts."""
    sentence = sentence.replace("hafta",        "have to"    )
    sentence = sentence.replace("over flowing", "overflowing")
    sentence = sentence.replace(" ok ",         " okay "     )
    sentence = sentence.replace(" ok,",         " okay,"     )
    return sentence

def clean_sentences(sentences: list[str]) -> list[str]:
    """Clean up various artifacts present in transcript sentence lists."""
    # Sometimes there are words in the reference like "you_know"
    sentences = [s.replace("_", " ").replace("-", " ") for s in sentences]

    # Ellipses ("..." or ".." often used to represent pauses in the IU transcripts)
    sentences = [s.replace("….",  ". ").replace("…",  ", ") for s in sentences]
    sentences = [s.replace("...", ". ").replace("..", ". ") for s in sentences]
    sentences = [s.replace("...", ". ").replace("..", ". ") for s in sentences]

    # Sometimes there are words they manually changed to contractions
    sentences = [replace_helper(s) for s in sentences]

    sentences = [s.replace("'s", " is") for s in sentences]

    return sentences

# --------------------------------------------------------------------------------
# Split utterances in to sentences (keeping punctuation)
# --------------------------------------------------------------------------------
def split_and_keep(text: str, delimiters: Iterable[str] = _EOS_CHARACTERS) -> List[str]:
    """
    Split text on EOS punctuation, keeping each delimiter attached to its sentence.

    Example: "Hello. World?" -> ["Hello.", "World?"]
    """
    pattern = f"([{''.join(map(re.escape, delimiters))}])"
    parts   = re.split(pattern, text)

    # Reattach each delimiter to the preceding text chunk
    result = [parts[i] + parts[i + 1] for i in range(0, len(parts) - 1, 2)]

    # Append any trailing text that didn't end with a delimiter
    if (len(parts) % 2 != 0) and parts[-1]:
        result.append(parts[-1])

    return [s.strip() for s in result if s.strip()]


# ================================================================================
# Perplexity Utterance Cleaning
# ================================================================================
def clean_utterances(utterances, MIN_UTT_WORDS: int = MIN_UTT_WORDS_DEFAULT) -> list:
    """Clean utterances and keep only those with >= MIN_UTT_WORDS words."""
    sentences = []
    for utt in utterances:
        words = str(utt).strip().split(" ")
        if len(words) < MIN_UTT_WORDS: continue

        clean_words = [re.sub(r'[^\w]', '', w.lower()) for w in words]

        sentences.append(" ".join(clean_words))

    return sentences

